INSERT INTO CLIENTE(ID, NOME) VALUES (1,'CAIO');
INSERT INTO CLIENTE(ID, NOME) VALUES (2,'PAULA');

INSERT INTO PRODUTO(ID, NOME, VALOR) VALUES (1, 'Notebook', 3330.0);
INSERT INTO PRODUTO(ID, NOME, VALOR) VALUES (2, 'Tv Smart', 34235.0);
INSERT INTO PRODUTO(ID, NOME, VALOR) VALUES (3, 'Geladeira', 5663.0);

INSERT INTO VENDA(ID, CLIENTE_ID, FRETE, TOTAL, CADASTRO) VALUES (1,1, 15.0, 2965.0, SYSDATE());

INSERT INTO ITEM(ID, VENDA_ID, PRODUTO_ID, QUANTIDADE) VALUES (1,1,1,1);
